GET http://localhost:8000/api

###

POST http://localhost:8000/api/sign

###

POST http://localhost:8000/api/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Imp1bHliYXRjaCIsImVtYWlsIjoianVseUBjbi5jb20ifSwiaWF0IjoxNjQ4MTM4NjgyfQ.pfKkOmhHdbhKs9anc7ci2v6JUQ3cLIOr9KcowhZgrRw
